# fly.toml app configuration file generated for kabini-proud-tree-2292 on 2025-09-30T12:17:24+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kabini-wild-sound-1399'
primary_region = 'bom'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_API_KEY = 'e244fca5e9bbe22e8b4885e9dc551b1b'
  SHOPIFY_APP_URL = 'https://kabini-wild-sound-1399.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
