# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e244fca5e9bbe22e8b4885e9dc551b1b"
name = "kabini"
application_url = "https://kabini-wild-sound-1399.fly.dev/"
embedded = true
handle = "kabini"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ "read_content" ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://kabini-wild-sound-1399.fly.dev/auth/callback",
  "https://kabini-wild-sound-1399.fly.dev/auth/shopify/callback",
  "https://kabini-wild-sound-1399.fly.dev/api/auth/callback"
]
